# Generated by Django 5.0.1 on 2024-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="shoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                ("sname", models.CharField(max_length=50)),
                ("sprice", models.IntegerField()),
                ("scolor", models.CharField(max_length=50)),
                (
                    "ssize",
                    models.CharField(
                        choices=[
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
