# Generated by Django 5.0.1 on 2024-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_order_orderitem_shippingaddress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="gymandaccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media")),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
