# Generated by Django 5.0.1 on 2024-02-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_gymandaccessories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymandaccessories",
            name="image",
            field=models.ImageField(upload_to="mediaa"),
        ),
    ]
