# Generated by Django 5.0.1 on 2024-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_gymandaccessories_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymandaccessories",
            name="image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
