# Generated by Django 5.0.1 on 2024-02-20 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_gymandaccessories_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gymandaccessories",
            old_name="image",
            new_name="simage",
        ),
    ]
