# Generated by Django 5.0.1 on 2024-02-20 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_gymandaccessories_simage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="gymandaccessories",
        ),
    ]
