# Generated by Django 5.0.1 on 2024-02-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_delete_gymandaccessories"),
    ]

    operations = [
        migrations.CreateModel(
            name="gymandaccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simage", models.ImageField(upload_to="gym_images/")),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
