# Generated by Django 5.0.1 on 2024-02-27 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_gymandaccessories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cartitem",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="shoes",
        ),
    ]
