# Generated by Django 5.0.1 on 2024-02-29 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_cartitem_gym_orderitem_products"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cartitem",
            table="cart_items_gym",
        ),
    ]
