# Generated by Django 5.0.1 on 2024-02-29 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_cartitem_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="gym",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="products",
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="cart_items",
        ),
    ]
