# Generated by Django 5.0.1 on 2024-02-29 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_cartitem_gym_orderitem_products_alter_cartitem_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cartitem",
            table="cart_items",
        ),
    ]
