# Generated by Django 5.0.1 on 2024-03-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_alter_cartitem_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tshirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tshirt_images")),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="shirt",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.tshirt"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="prod",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.tshirt"
            ),
        ),
    ]
