# Generated by Django 5.0.1 on 2024-03-02 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_tshirt_cartitem_shirt_orderitem_prod"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorSport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tshirt_images")),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="ms",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.motorsport",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="prods",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.motorsport",
            ),
        ),
    ]
