# Generated by Django 5.0.1 on 2024-03-03 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="student",
            new_name="details",
        ),
    ]
